server:
  port: 8001
  compression:
    enabled: true
    min-response-size: 1
# undertow
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2
    access-log:
      enabled: true
      dir: target/logs
      pattern: combined

spring:
  name: dubbo-spring-boot-consumer
  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

dubbo:
  application:
    name: ${spring.name}
  registry: ## Dubbo Registry
    address: zookeeper://127.0.0.1:2181
    timeout: 3000