spring:
  name: dubbo-spring-boot-provider
  devtools:
    restart:
      enabled: true

dubbo:
  application:
    name: ${spring.name}
  scan:
    base-packages: cn.z201.io.learning.rpc.micro.provider.service
  protocol:
    name: dubbo
    port: 12345
  registry: ## Dubbo Registry
    address: zookeeper://127.0.0.1:2181
    timeout: 3000
  metadata-report:
      address: zookeeper://127.0.0.1:2181

