spring:
  name: dubbo-spring-boot-mock-test
  devtools:
    restart:
      enabled: true

dubbo:
  application:
    name: ${spring.name}
  registry: ## Dubbo Registry
    address: zookeeper://127.0.0.1:2181
    timeout: 3000

